WEB/Controllers/CORREOController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webSMSAxede.Models;
using webSMSAxede.Helper;
using System.Configuration;
using System.Data.OleDb;
using System.Data;
using System.IO;
using System.Web.Helpers;
using System.Web.Configuration;
using MODELO;

namespace WEB.Controllers
{
    public class CORREOController : Controller
    {
        private GestionRegistros _registros = null;
        notifixEntities ne = new notifixEntities();

        private List<ContactoModel> pObtenerListado
        {
            get
            {
                _registros = new GestionRegistros();
                List<ContactoModel> objLista = _registros.pObtenerListado;
                _registros = null;
                return objLista;
            }
            set
            {
                _registros = new GestionRegistros();
                _registros.pObtenerListado = value;
                _registros = null;
            }
        }

        public JsonResult ObtenerListado()
        {
            List<ContactoModel> listContacto = pObtenerListado.ToList();

            return Json(listContacto, JsonRequestBehavior.AllowGet);
        }
        public ActionResult EmailGeneral()
        {
            string msg = "";
            if (Session["mensaje"] != null)
                msg = Session["mensaje"].ToString();
            return View("EmailGeneral", pObtenerListado);
        }

        public ActionResult EmailIndividual()
        {
            string msg = "";
            if (Session["mensaje"] != null)
                msg = Session["mensaje"].ToString();
            return View("EmailIndividual", pObtenerListado);
        }

        public JsonResult Eliminar(string id, string msg)
        {
            try
            {
                if (Session["mensaje"] == null)
                {
                    Session["mensaje"] = msg;

                }
                else
                {
                    if (Session["mensaje"].ToString() != msg)
                    {
                        Session["mensaje"] = msg;
                    }
                }

                List<ContactoModel> listContacto = pObtenerListado;
                var registro = listContacto.FirstOrDefault(k => k.Celular == id);
                if (registro != null)
                {
                    listContacto.Remove(registro);
                    pObtenerListado = listContacto;
                }
                var respuesta = new { estado = "ok", mensaje = "" };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
            catch (Exception error)
            {
                Reportar("Adicionar", "error: " + error.Message);
                var respuesta = new { estado = "nok", mensaje = error.Message };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }

        }

        //Inicio Adicionar CORREO-GENERAL
        public JsonResult Adicionar(ContactoModel contacto)
        {
            try
            {


                if (Session["mensaje"] == null)
                {
                    Session["mensaje"] = contacto.msg;

                }
                else
                {
                    if (Session["mensaje"].ToString() != contacto.msg)
                    {
                        Session["mensaje"] = contacto.msg;
                    }
                }

                if (pObtenerListado.Any(k => k.Email == contacto.Email)) throw new Exception("Ya existe un contacto con el correo electronico: " + contacto.Email + ".\nPor favor verifique!.");
                List<ContactoModel> listContacto = pObtenerListado;
                contacto.Enviar = true;
                listContacto.Add(contacto);
                pObtenerListado = listContacto;
                var respuesta = new { estado = "ok", mensaje = "" };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
            catch (Exception error)
            {
                Reportar("Adicionar", "error: " + error.Message);
                var respuesta = new { estado = "nok", mensaje = error.Message };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
        }
        //Fin Adicionar CORREO-GENERAL

        //Inicio de Adicionar CORREO-INDIVIDUAL
        public JsonResult AdicionarIndiv(ContactoModel contacto)
        {
            try
            {


                if (Session["mensaje"] == null)
                {
                    Session["mensaje"] = contacto.msg;

                }
                else
                {
                    if (Session["mensaje"].ToString() != contacto.msg)
                    {
                        Session["mensaje"] = contacto.msg;
                    }
                }

                if (pObtenerListado.Any(k => k.Email == contacto.Email)) throw new Exception("Ya existe un contacto con el correo electronico: " + contacto.Email + ".\nPor favor verifique!.");
                List<ContactoModel> listContacto = pObtenerListado;
                contacto.Enviar = true;
                listContacto.Add(contacto);
                pObtenerListado = listContacto;
                var respuesta = new { estado = "ok", mensaje = "" };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
            catch (Exception error)
            {
                Reportar("AdicionarIndiv", "error: " + error.Message);
                var respuesta = new { estado = "nok", mensaje = error.Message };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
        }
        //Fin de Adicionar CORREO-INDIVIDUAL

        public JsonResult ActualizarEnviar(string id, bool estado)
        {
            try
            {
                List<ContactoModel> listContacto = pObtenerListado;
                var registro = listContacto.FirstOrDefault(k => k.Celular == id);
                if (registro != null)
                {
                    registro.Enviar = estado;
                    pObtenerListado = listContacto;
                }
                var respuesta = new { estado = "ok", mensaje = "" };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
            catch (Exception error)
            {
                Reportar("ActualizarEnviar", "error: " + error.Message);
                var respuesta = new { estado = "nok", mensaje = error.Message };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult CargarArchivo()
        {
            Reportar("CargarArchivo", "Ingresa");
            try
            {

                ProcesarArchivo();
                var respuesta = new { estado = "ok", mensaje = "" };
                TempData["MensajeInformativo"] = "Carga correcta!";
                Reportar("CargarArchivo", "termina");
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
            catch (Exception error)
            {
                Reportar("CargarArchivo", "error: " + error.Message);
                var respuesta = new { estado = "nok", mensaje = error.Message };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }

        }

        public JsonResult EnviarMensajes(string texto)
        {
            try
            {
                List<ContactoModel> listContacto = pObtenerListado;
                if (listContacto.Count == 0) throw new Exception("no existen contáctos para enviar mensajes!");
                var qLista = pObtenerListado.Where(k => k.Enviar).ToList();
                ProcesarMensajes(qLista, texto);
                pObtenerListado = new List<ContactoModel>();
                var respuesta = new { estado = "ok", mensaje = "" };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
            catch (Exception error)
            {
                Reportar("EnviarMensajes", "error: " + error.Message);
                var respuesta = new { estado = "nok", mensaje = error.Message };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
        }

        private void ProcesarMensajes(List<ContactoModel> lsContactos, string texto)
        {
            var idcorreo = (from c in ne.t_email
                            select c).Max(c => c.Id);
            var host = (from s in ne.t_email
                        where s.Id == idcorreo
                        select s.HostEmail).First();
            var puerto = (from s in ne.t_email
                          where s.Id == idcorreo
                          select s.Puerto).First();
            var correo = (from s in ne.t_email
                          where s.Id == idcorreo
                          select s.Correo).First();
            var clave = (from s in ne.t_email
                         where s.Id == idcorreo
                         select s.Clave).First();
            var certificado = (from s in ne.t_email
                               where s.Id == idcorreo
                               select s.Certificado).First();

            string mensaje ;
            string email ;
            string asunto ;
            WebMail.SmtpServer = host.Trim();
            WebMail.SmtpPort = Convert.ToInt32(puerto);
            WebMail.SmtpUseDefaultCredentials = true;
            WebMail.EnableSsl = Convert.ToBoolean(certificado);  
            WebMail.UserName = correo.Trim();
            WebMail.Password = clave.Trim();
            WebMail.From = correo.Trim();
            string nota = "Favor no responder este mensaje que ha sido emitido automáticamente por el sistema de Notificaciones de Axede S.A";

            lsContactos.ForEach(delegate (ContactoModel item)
            {
                try
                {
                   

WEB/Views/CORREO/CargaArchivo.cshtml
@{
    ViewBag.Title = "Carga Archivo";
}

<div class="text-center">
    <h2><strong>CARGAR ARCHIVO</strong></h2>
</div><br /><br />

@using (Html.BeginForm("CargaArchivo", "CORREO", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        <div class="row">
            <div class="col-5"></div>
            <div class="form-group col-2">
                <label class="btn btn-primary btn-block" for="fileInput">
                    <input id="fileInput" name="fileInput" type="file" style="display:none" onchange="$('#upload-file-info').html(this.files[0].name)">
                    Seleccionar archivo
                </label>
                <span class='label label-info' id="upload-file-info"></span>
            </div>
            <div class="col-5"></div>
        </div>

        <div class="row">
            <div class="col-5"></div>
            <div class="form-group col-2">
                <input type="submit" value="Cargar archivo" class="btn btn-primary btn-block" />
            </div>
            <div class="col-5"></div>
        </div>

        <div class="row">
            <div class="col-5"></div>
            <div class="form-group col-2">
                <input type="button" value="Regresar" class="btn btn-primary btn-block" id="btnregresar" onclick="regresar();" />
            </div>
            <div class="col-5"></div>
        </div>
    </div>
}

<br />
<script type="text/javascript">
    $(function () {
        $("#btnregresar").click(function () {
            window.location.href = "@Url.Action("EmailGeneral", "CORREO")";
        });
    });

</script>

WEB/Views/CORREO/CargaArchivoInd.cshtml
@{
    ViewBag.Title = "Carga Archivo";
}

<div class="text-center">
    <h2><strong>CARGAR ARCHIVO</strong></h2>
</div><br /><br />

@using (Html.BeginForm("CargaArchivoInd", "CORREO", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        <div class="row">
            <div class="col-5"></div>
            <div class="form-group col-2">
                <label class="btn btn-primary btn-block" for="fileInput">
                    <input id="fileInput" name="fileInput" type="file" style="display:none" onchange="$('#upload-file-info').html(this.files[0].name)">
                    Seleccionar archivo
                </label>
                <span class='label label-info' id="upload-file-info"></span>
            </div>
            <div class="col-5"></div>
        </div>

        <div class="row">
            <div class="col-5"></div>
            <div class="form-group col-2">
                <input type="submit" value="Cargar archivo" class="btn btn-primary btn-block" />
            </div>
            <div class="col-5"></div>
        </div>

        <div class="row">
            <div class="col-5"></div>
            <div class="form-group col-2">
                <input type="button" value="Regresar" class="btn btn-primary btn-block" id="btnregresar" onclick="regresar();" />
            </div>
            <div class="col-5"></div>
        </div>
    </div>
}

<br />
<script type="text/javascript">
    $(function () {
        $("#btnregresar").click(function () {
            window.location.href = "@Url.Action("EmailIndividual", "CORREO")";
        });
    });

</script>

WEB/Views/CORREO/EmailGeneral.cshtml
@{
    ViewBag.Title = "EMAIL-GENERAL";
}


<script src="~/Scripts/MensajeTexto/usuario.js" type="text/javascript"></script>

<div class="text-center">
    <h2><strong>EMAIL GENERAL</strong></h2>
</div>

<br /><br />
<!--Inicio de botones-->
<div class="row">
    &nbsp;&nbsp;&nbsp;
    <div class="form-group">
        <button id="btnGeneral" type="button" class="btn btn-primary col-xs-12 col-sm-12 col-md-12 col-lg-12" data-toggle="modal" data-target="#myModal" onclick="clearTextBox(); limpiar_adicionar_general_email();" style="display:block;">Adicionar</button>
    </div>
    &nbsp;&nbsp;
    <div class="form-group">
        <button type="button" class="btn btn-primary col-xs-12 col-sm-12 col-md-12 col-lg-12" id="btncargar">Carga archivo</button>
    </div>
</div>
<!--Inicio de botones-->
<!--Inicio de tabla General-->
<div class="row">
    <div class="text-center col-md-12" id="tablatitulo" style="display:none;">

        <table class="table table-bordered">

            <thead class="thead-light">
                <tr>
                    <th>
                        Título
                    </th>
                    <th>
                        Nombre
                    </th>
                    <th>
                        Correo
                    </th>
                    <th>
                        Asunto
                    </th>
                    <th>
                        Enviar
                    </th>
                    <th>
                        Borrar
                    </th>
                </tr>
            </thead>
            <tbody class="tbody"></tbody>
        </table>
    </div>
</div>
<!--Fin de tabla General-->
<br />
<!--Inicio de tabla Mensaje GENERAL-->
<div>
    @{
        string texto = "su contrato de mantenimiento de la plataforma XXX se vence en los proximos dias. Favor comunicarse con XXX al telefono XXX.";
    }
    <div class="row form-group text-center">
        <h4 class="col-12 text-dark"><strong>MENSAJE</strong></h4>
    </div>
    <div class="row">
        <div class="col-0"></div>
        <div class="col-12">
            @if (Session["mensaje"] != null)
            {
                <textarea id="txttexto" rows="4" style="max-width:100%;width:100%; border-radius:10px;"  class="form-control ">@Session["mensaje"].ToString()</textarea>}
            else
            {
                <textarea id="txttexto" rows="4" style="max-width:100%;width:100%; border-radius:10px;"  class="form-control ">@texto</textarea>
            }
        </div>
        <div class="col-0"></div>
    </div>

    <br />
    <!--Inicio de Botones-->
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <input id="btnenviar" type="button" value="Enviar mensaje" class="btn btn-primary  col-xs-12 col-sm-12 col-md-12 " />
        </div>
        <div class="col-4"></div>
    </div>
    <!--Inicio de Botones-->

</div>
<!--Fin de tabla Mensaje GENERAL-->
<br />
<!--Inicio de icono de espera-->
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <p align="center"><img src="~/Images/wait.gif" id="imgespere" alt="Por favor espere mientras el sistema procesa su petición!" style="display:none;width:100px;height:100px;" /></p>
    </div>
    <div class="col-4"></div>
</div>
<!--Fin de icono de espera-->
<!--Inicio de Modal SMS-GENERAL-->
<div class="modal fade" id="myModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h5 class="modal-title">ADICIONAR EMAIL-GENERAL</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <br />
                <div class="form-group row">
                    <label for="tratamiento" class="col-3 d-flex justify-content-end"><strong>TÍTULO</strong></label>
                    <select id="tratamiento" name="tratamiento" class="selectpicker form-control col-8 d-flex justify-content-start">
                        <option value="Sr">Sr</option>
                        <option value="Sra">Sra</option>
                        <option value="Ing">Ing</option>
                    </select>
                </div>
                <div class="form-group row">
                    <label for="nombre" class="col-3 d-flex justify-content-end"><strong>NOMBRES</strong></label>
                    <input type="text" class="form-control col-8 d-flex justify-content-start" id="nombre" placeholder="NOMBRE"  />
                </div>
                <div class="form-group row">
                    <label for="correo" class="col-3 d-flex justify-content-end"><strong>CORREO</strong></label>
                    <input type="email" class="form-control col-8 d-flex justify-content-start" id="correo" placeholder="CORREO ELECTRONICO"  />
                </div>
                <div class="form-group row">
                    <label for="asunto" class="col-3 d-flex justify-content-end"><strong>ASUNTO</strong></label>
                    <input type="text" class="form-control col-8 d-flex justify-content-start" id="asunto" placeholder="ASUNTO DE CORREO"  />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnAdd" onclick="return Adicionar();">Adicionar</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>
<!--Fin de Modal SMS-GENERAL-->
<!--Inicio de javascript-->
<script type="text/javascript">

    var ruta = '../MensajeTexto/';

    $(document).ready(function () {
        CargarVista();
    });

    //Inicio Funcion CargarVista() al momento de adicionar manualmente : SMS-GENERAL
    function CargarVista() {
        var res = "0";
        $.ajax({
            url:'@Url.Action("ObtenerListado", "CORREO")',
            type: "POST",
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
                var html = '';
                $.each(result, function (key, item) {
                  html += '<tr>';
                    html += '<td>' + item.Tratamiento + '</td>';
                    html += '<td>' + item.Nombre + '</td>';
                    html += '<td>' + item.Email + '</td>';
                    html += '<td>' + item.AsuntoEmail + '</td>';
                    html += "<td align='center'>" + CrearCheckBox(item.Celular, item.Enviar) + "</td>";
                    html += '<td> <a class="fa fa-remove" href="#" onclick="Eliminar(' + item.Celular + ');"> <span class="glyphicon glyphicon-trash"> </a> </td>';
                    html += '</tr>';
                    res = "1";
                });

                if (res == "1")
                {
                    document.getElementById("tablatitulo").style.display = "block";
                    //document.getElementById("tablaSMS").style.display = "block";
                }
                else
                    document.getElementById("tablatitulo").style.display = "none";

                $('.tbody').html(html);

            },
            error: function (errormessage) {
            }
        });
    }
    //Fin Funcion CargarVista() al momento de adicionar manualmente : SMS-GENERAL

    //Inicio de funcion adicionar desde modal : SMS GENERAL
    function Adicionar() {
        var objcontacto = {
            ID: 0,
            Nombre: $('#nombre').val(),
            Email: $('#correo').val(),
            AsuntoEmail: $('#asunto').val(),
            Tratamiento: $('#tratamiento').val(),
            msg: $('#txttexto').val()
        };
        $.ajax({
            url: '@Url.Action("Adicionar", "CORREO")',
            data: JSON.stringify({ 'contacto': objcontacto }),
            type: "POST",
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            async: false,
            success: function (result)
            {
              $('#myModal').modal('hide');
              $('#myModal').hide();// .modal('hide');
              if (result.estado == 'ok') CargarVista();//location.reload();
              else alert(result.mensaje);
              location.reload();
            },
            error: function (errormessage)
            {
              $('#myModal').modal('hide');
                alert(errormessage.responseText);
            }
        });
    }
    //Fin de funcion adicionar desde modal : SMS GENERAL

    //Inicio de eliminar
    function Eliminar(ID) {
      var ans = confirm("Confirma que desea remover el registro?");

        if (ans) {
            $.ajax({
                url: '@Url.Action("Eliminar", "CORREO")',
                type: "POST",
                contentType: "application/json;charset=UTF-8",
                dataType: "json",
                data: JSON.stringify({ 'id': parseInt(ID) ,'msg': $('#txttexto').val()}),
                async:false,
                success: function (result) {

                    if (result.estado == 'ok') { CargarVista(); location.reload(); }
                    else alert(result.mensaje);
                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                }
            });
        }
        return false;
    }
    //Fin de eliminar

    //Inicio de Boton enviar
    $(document).ready(function () {
        $("#btnenviar").click(function () {
            var texto = $('#txttexto');
            if (texto.val() == '') {
                alert('Debe ingresar un texto para los mensajes!');
                texto.focus();
                return false;
            }
            EnviarMensajes(texto.val());
			LimpiarTabla();
			window.location.href = '@Url.Action("Index", "Home")';
        });

    });
    //Fin de Botin enviar

    //Inicio de funcion enviarmensaje()
    function EnviarMensajes(mensaje) {
        $('#btnenviar').hide();
        $('#imgespere').show();
        $.ajax({
          url: '@Url.Action("EnviarMensajes", "CORREO")',
          type: "POST",
          contentType: "application/json;charset=UTF-8",
          dataType: "json",
          data: JSON.stringify({ 'texto': mensaje }),
          async: true,
          success: function (result) {
            $('#imgespere').hide();
            $('#btnenviar').show();
            if (result.estado == 'ok') {
                alert('Mensajes enviados correctamente.!');
                
                location.reload();
                location.href = '@Url.Action("Index", "Home")';
            }
            else {
                alert(result.mensaje);
                
            }
          },
          error: function (errormessage) {
            $('#btnenviar').show();
            $('#imgespere').hide();
          }
        });
    }
    //Fin de funcion enviarmensaje()

    //Inicio de Boton CargarArchivo
    $('#btncargar').on('click', function ()
    {
        var url = '@Url.Action("CargaArchivo", "CORREO")?msg=' + $('#txttexto').val();
        window.location.href = url;
    })
    //Fin de Boton CargarArchivo

    //Inicio de funcion CheckBox
    function CrearCheckBox(ID, Enviar) {
        var control = "<input name='chkenviar' type='checkbox' onclick='OperarCheckBox(this," + ID + ");' ";
        if (Enviar == true)
            control += "checked";
        control += " />";

        return control;

    }
    //Fin de funcion Checkbox

    //Inicio de funcion operarCheckbox
    function OperarCheckBox(cb, valor) {

    $.ajax({
      url: '@Url.Action("ActualizarEnviar", "CORREO")',
      type: "POST",
      contentType: "application/json;charset=UTF-8",
      dataType: "json",
      data: JSON.stringify({ 'id': valor, 'estado': cb.checked }),
      async: false,
      success: function (result) {
        if (result.estado != 'ok') alert(result.mensaje);
      },
      error: function (errormessage) {

      }
    });
    }
    //Fin de funcion Operar checkbox

    //Funcion verificar celular
    $(document).ready(function () {
        $("#celular").keydown(function (e) {

            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                (e.keyCode === 65 && (e.ctrlKey === true || e.metaKey === true)) ||
                (e.keyCode >= 35 && e.keyCode <= 40)) {
                return;
            }

            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                e.preventDefault();
            }
        });
    });
    //Fin de funcion verificar celular

    //Inicio de funcion limpiartabla()
    function LimpiarTabla() {
    $.ajax({
      url: '@Url.Action("LimpiarTabla", "CORREO")',
      type: "POST",
      contentType: "application/json;charset=UTF-8",
      dataType: "json",
      data: '',
      async: false,
      success: function (result) {

        if (result.estado == 'ok') $('.tbody').html('');
      },
      error: function (errormessage) {

      }
    });
    return false;
    }
    //Fin de funcion limpiartabla

</script>
<script src="~/Scripts/mensajes.js"></script>
<script src="~/Scripts/Alertas.js"></script>


<!--Fin de javascript-->