WEB/Controllers/ConfiguracionEmailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MODELO;

namespace WEB.Controllers
{
    public class ConfiguracionEmailController : Controller
    {
        notifixEntities ne = new notifixEntities();
        public ActionResult NuevoAjusteEMAIL()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NuevoAjusteEMAIL(string txtNomConfigEmail, string txtEmail, string txtClave, string txtHost, int txtPuerto, string txtCertificado)
        {
            DateTime Hoy = DateTime.Today;
            string fecha_actual = Hoy.ToString("dd-MM-yyyy");
            bool valor;

            if (txtCertificado == "1")
            { valor = true; }
            else
            { valor = false; }

            try
            {
                ne.ntx_NuevaConfEmail(txtNomConfigEmail, txtEmail, txtClave, txtHost, txtPuerto, fecha_actual, valor);
                ViewBag.Mensaje = "ok";
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "no";
                return View();
            }
            
        }
    }
}

WEB/Controllers/ConfiguracionSmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MODELO;

namespace WEB.Controllers
{
    public class ConfiguracionSmsController : Controller
    {
        notifixEntities ne = new notifixEntities();
        // GET: ConfiguracionSms
        public ActionResult NuevoAjusteSMS()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NuevoAjusteSMS(string txtNomConfigSms, string txtUrl, string txtMetodo)
        {
            DateTime Hoy = DateTime.Today;
            string fecha_actual = Hoy.ToString("dd-MM-yyyy");

            try
            {
                ne.ntx_NuevaConfSms(txtNomConfigSms, txtUrl, txtMetodo, fecha_actual);
                ViewBag.mensaje = "ok";
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.mensaje = "No";
                return View();
            }
        }
    }
}

WEB/Controllers/SMSController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webSMSAxede.Helper;
using webSMSAxede.Models;

namespace WEB.Controllers
{
    public class SMSController : Controller
    {
        private GestionRegistros _registros = null;

        private List<ContactoModel> pObtenerListado
        {
            get
            {
                _registros = new GestionRegistros();
                List<ContactoModel> objLista = _registros.pObtenerListado;
                _registros = null;
                return objLista;
            }
            set
            {
                _registros = new GestionRegistros();
                _registros.pObtenerListado = value;
                _registros = null;
            }
        }

        public JsonResult ObtenerListado()
        {
            List<ContactoModel> listContacto = pObtenerListado.ToList();

            return Json(listContacto, JsonRequestBehavior.AllowGet);
        }
        public ActionResult SmsGeneral()
        {
            string msg = "";
            if (Session["mensaje"] != null)
                msg = Session["mensaje"].ToString();
            return View("SmsGeneral", pObtenerListado);
        }

        public ActionResult SmsIndividual()
        {
            string msg = "";
            if (Session["mensaje"] != null)
                msg = Session["mensaje"].ToString();
            return View("SmsIndividual", pObtenerListado);
        }

        public JsonResult Eliminar(string id, string msg)
        {
            try
            {
                if (Session["mensaje"] == null)
                {
                    Session["mensaje"] = msg;

                }
                else
                {
                    if (Session["mensaje"].ToString() != msg)
                    {
                        Session["mensaje"] = msg;
                    }
                }

                List<ContactoModel> listContacto = pObtenerListado;
                var registro = listContacto.FirstOrDefault(k => k.Celular == id);
                if (registro != null)
                {
                    listContacto.Remove(registro);
                    pObtenerListado = listContacto;
                }
                var respuesta = new { estado = "ok", mensaje = "" };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
            catch (Exception error)
            {
                Reportar("Adicionar", "error: " + error.Message);
                var respuesta = new { estado = "nok", mensaje = error.Message };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }

        }

        //Inicio Adicionar SMS-GENERAL
        public JsonResult Adicionar(ContactoModel contacto)
        {
            try
            {


                if (Session["mensaje"] == null)
                {
                    Session["mensaje"] = contacto.msg;

                }
                else
                {
                    if (Session["mensaje"].ToString() != contacto.msg)
                    {
                        Session["mensaje"] = contacto.msg;
                    }
                }

                if (pObtenerListado.Any(k => k.Celular == contacto.Celular)) throw new Exception("Ya existe un contacto con el número celular: " + contacto.Celular + ".\nPor favor verifique!.");
                List<ContactoModel> listContacto = pObtenerListado;
                contacto.Enviar = true;
                listContacto.Add(contacto);
                pObtenerListado = listContacto;
                var respuesta = new { estado = "ok", mensaje = "" };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
            catch (Exception error)
            {
                Reportar("Adicionar", "error: " + error.Message);
                var respuesta = new { estado = "nok", mensaje = error.Message };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
        }
        //Fin Adicionar SMS-GENERAL

        //Inicio de Adicionar SMS-INDIVIDUAL
        public JsonResult AdicionarIndiv(ContactoModel contacto)
        {
            try
            {


                if (Session["mensaje"] == null)
                {
                    Session["mensaje"] = contacto.msg;

                }
                else
                {
                    if (Session["mensaje"].ToString() != contacto.msg)
                    {
                        Session["mensaje"] = contacto.msg;
                    }
                }

                if (pObtenerListado.Any(k => k.Celular == contacto.Celular)) throw new Exception("Ya existe un contacto con el número celular: " + contacto.Celular + ".\nPor favor verifique!.");
                List<ContactoModel> listContacto = pObtenerListado;
                contacto.Enviar = true;
                listContacto.Add(contacto);
                pObtenerListado = listContacto;
                var respuesta = new { estado = "ok", mensaje = "" };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
            catch (Exception error)
            {
                Reportar("AdicionarIndiv", "error: " + error.Message);
                var respuesta = new { estado = "nok", mensaje = error.Message };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
        }
        //Fin de Adicionar SMS-INDIVIDUAL

        public JsonResult ActualizarEnviar(string id, bool estado)
        {
            try
            {
                List<ContactoModel> listContacto = pObtenerListado;
                var registro = listContacto.FirstOrDefault(k => k.Celular == id);
                if (registro != null)
                {
                    registro.Enviar = estado;
                    pObtenerListado = listContacto;
                }
                var respuesta = new { estado = "ok", mensaje = "" };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
            catch (Exception error)
            {
                Reportar("ActualizarEnviar", "error: " + error.Message);
                var respuesta = new { estado = "nok", mensaje = error.Message };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult CargarArchivo()
        {
            Reportar("CargarArchivo", "Ingresa");
            try
            {

                ProcesarArchivo();
                var respuesta = new { estado = "ok", mensaje = "" };
                TempData["MensajeInformativo"] = "Carga correcta!";
                Reportar("CargarArchivo", "termina");
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
            catch (Exception error)
            {
                Reportar("CargarArchivo", "error: " + error.Message);
                var respuesta = new { estado = "nok", mensaje = error.Message };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }

        }

        public JsonResult EnviarMensajes(string texto)
        {
            try
            {
                List<ContactoModel> listContacto = pObtenerListado;
                if (listContacto.Count == 0) throw new Exception("no existen contáctos para enviar mensajes!");
                var qLista = pObtenerListado.Where(k => k.Enviar).ToList();
                ProcesarMensajes(qLista, texto);
                pObtenerListado = new List<ContactoModel>();
                var respuesta = new { estado = "ok", mensaje = "" };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
            catch (Exception error)
            {
                Reportar("EnviarMensajes", "error: " + error.Message);
                var respuesta = new { estado = "nok", mensaje = error.Message };
                return Json(respuesta, JsonRequestBehavior.AllowGet);
            }
        }

        private void ProcesarMensajes(List<ContactoModel> lsContactos, string texto)
        {
            string Contenido;
            string baseContenido = "{0} {1} {2}";
            lsContactos.ForEach(delegate (ContactoModel item)
            {
                if (lsContactos.Count <= 1 && texto != "")
                {
                    Contenido = string.Format(baseContenido, item.Tratamiento.ToUpper(), item.Nombre.ToUpper(), texto.Trim());
                }
                else if (lsContactos.Count > 1 && texto != "")
                {
                    Contenido = string.Format(baseContenido, item.Tratamiento.ToUpper(), item.Nombre.ToUpper(), texto.Trim());
                }
                else if (lsContactos.Count <= 1 && texto == "")
                {
                    Contenido = string.Format(baseContenido, item.Tratamiento.ToUpper(), item.Nombre.ToUpper(), item.msg.Trim());
                }
                else if(lsContactos[0].msg != lsContactos[1].msg || texto == "")
                {                     
                    Contenido = string.Format(baseContenido, item.Tratamiento.ToUpper(), item.Nombre.ToUpper(), item.msg.Trim());
                }
                else
                {
                    Contenido = string.Format(baseContenido, item.Tratamiento.ToUpper(), item.Nombre.ToUpper(), texto.Trim());
                }




                webSMSAxede.Helper.GestionMensaje objGestion = new webSMSAxede.Helper.GestionMensaje();
                objGestion.Enviar(item.Celular, Contenido);
                objGestion = null;
            }
            );
        }

        private void ProcesarArchivo()
        {
            string RutaArchivo = "";
            try
            {

                #region MyRegion
                try
                {

WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/stylos.css" />
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css">
    <link rel="stylesheet" href="~/Content/toastr.css"/>
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    @*<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>*@
    <title>@ViewBag.Title - NOTIFIX</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-expand navbar-dark  fixed-top" style="background-color: #A43A62;">

        <div class="container">
            @*<a class="navbar-brand" href='@Url.Action("Index", "Home")' style="font-family: 'Fredoka One', cursive;">AXEDE</a>*@
            <a class="navbar-brand" href='@Url.Action("Index", "Home")'>
                <img src="~/Images/NOTIFIXblanco-x.png" width="80" height="35" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav ">
                    <li class="nav-item active mr-2" style="font-family: 'Fredoka One', cursive;">
                        <a class="nav-link" href='@Url.Action("Index", "Home")'><i class="fas fa-home"></i> Inicio <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown active mr-2" style="font-family: 'Fredoka One', cursive;">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-comments"></i> Sms
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href='@Url.Action("SmsGeneral", "SMS")'>General</a>
                            <a class="dropdown-item" href='@Url.Action("SmsIndividual", "SMS")'>Individual</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown active mr-2" style="font-family: 'Fredoka One', cursive;">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-at"></i> Email
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href='@Url.Action("EmailGeneral", "CORREO")'>General</a>
                            <a class="dropdown-item" href='@Url.Action("EmailIndividual", "CORREO")'>Individual</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown active mr-2" style="font-family: 'Fredoka One', cursive;">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-cog"></i> Ajustes
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href='@Url.Action("NuevoAjusteSMS", "ConfiguracionSms")'>Sms</a>
                            <a class="dropdown-item" href='@Url.Action("NuevoAjusteEMAIL", "ConfiguracionEmail")'>Email</a>
                        </div>
                    </li>
                    <li class="nav-item active mr-2" style="font-family: 'Fredoka One', cursive;">
                        <a class="nav-link" href="#"><i class="fas fa-ambulance"></i> Ayuda</a>
                    </li>
                </ul>
            </div>

        </div>
    </div>
    <div class="container body-content">
        <br />
        @RenderBody()

        <footer class="container">
            <div class="row">
                <div class="col-md-6 text-left d-flex align-self-end" style="display: inline-block; font-family: 'Fredoka One', cursive;"><p>&copy; @DateTime.Now.Year - Axede Notifix </p></div>
                <div class="col-md-6 text-right align-self-end" style="padding-bottom:1px;"><img src="~/Images/NOTIFIX.jpg" style="height:50%; width:35%; display: inline-block;" /></div>
            </div>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/toastr.js"></script>
</body>
</html>